### PR TITLE
ISSUE_TEMPLATE.md: Nudge contributors to specify episodes unambigously

### PR DESCRIPTION
**Pull request by katrinleinweber**
See https://github.com/swcarpentry/r-novice-inflammation/issues/401 > 3.

### CODE REVIEW

**Comment by raynamharris** [comment]
Yes! This is an excellent suggestions. Thank you @katrinleinweber

**Comment by maxim-belkin** [comment]
LGTM. I've requested a review from @ErinBecker who added Issue Template originally.

**Comment by ErinBecker** [comment]
LGTM! Thanks @katrinleinweber!

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Pull request merged**
