### PR TITLE
added about the discussion stage to the LC description

### PR DESCRIPTION
**Pull request by tracykteal**
From discussions with @weaverbel @libcce and Executive Council, added about the discussion stage to the Library Carpentry description.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
I'd add it to the end of the description as I think it's more important to introduce the entity first.

**Comment by maxim-belkin** [comment]
Side note: this PR has to either be submitted against the `fix-311` branch or wait until #317 is merged

**Comment by tracykteal** [comment]
Thanks @maxim-belkin that sounds good. I see it should have gone somewhere else. Do you want me to close this PR and move?

**Comment by maxim-belkin** [comment]
> Do you want me to close this PR and move?

No-no. We'll take care of this but @rgaiacs prefers to [keep PRs open](https://github.com/carpentries/styles/pull/153#issuecomment-396892748) :)

**Comment by fmichonneau** [comment]
thanks for this update!

**Pull request merged**
