### PR TITLE
Harmonise code style through .editorconfig

### PR DESCRIPTION
**Pull request by katrinleinweber**
Draft implementation of https://github.com/swcarpentry/styles/issues/131 's suggestion.

### CODE REVIEW

**Comment by rgaiacs** [comment]
@katrinleinweber Thanks for the pull request. To accept it I would like to have come continuous integration (see http://pydocs.editorconfig.org/en/latest/command_line_usage.html) to enforce contributions to follow the rules.

cc @fmichonneau

**Comment by katrinleinweber** [comment]
Hey, come on ;-D Currently, nothing is enforced automatically. So this step to `.editorconfig` already provides some of that "enforcement". At the source. Subliminally. And largely without anyone having to lift a finger. A clear benefit is within reach.

Setting up a CI pipeline is barely within my reach and thus heavy lifting. I did want to learn it at some point anyway, but I can't promise how soon I'll find the time.

**Comment by fmichonneau** [comment]
Thanks for this @katrinleinweber I'm going to look into this more. I'm not very familiar with using .editorconfig at the moment. Re: implementing the CI, you don't have to worry about this, it's something I'm  working on at the moment.

**Comment by maxim-belkin** [comment]
@katrinleinweber, how about `[*.md]` section and `max_line_length` setting? Otherwise, this PR looks good to me.

Regarding CI: IMHO we should not bother with adding EditorConfig checks to CI...

**Comment by katrinleinweber** [comment]
And which number of characters for `max_line_length`? 80 is RStudio's default, but [Python demands 79](https://www.python.org/dev/peps/pep-0008/#maximum-line-length).

**Comment by maxim-belkin** [comment]
in `lesson-check` it is set to 100... 🙄

**Comment by katrinleinweber** [comment]
Ah, right! Thanks for the reminder. So, should we duplicate that piece of info here?

IMHO, it seems reasonable to let `.editorconfig` serve as the "1st line of defense" (so to speak) and "[lesson_check.py](https://github.com/swcarpentry/styles/blob/0e0f2bf4e396419a46760d0add6af054cd1c512c/bin/lesson_check.py#L102)" as the last. But puts the responsibility to maintain keep both places in sync onto the maintainers of this styles repo.

However, an alternative approach would be to remove that setting from the checker then and ask lesson maintainers to use an `.editorconfig`-respecting editor or to align their RStudio settings with it.

**Comment by maxim-belkin** [comment]
> But puts the responsibility to maintain keep both places in sync onto the maintainers of this styles repo.

This can be solved either by adding clear comments to these lines **and/or** with a wiki.

**Pull request merged**
