### PR TITLE
Improve all in one

### PR DESCRIPTION
**Pull request by fmichonneau**
* it seems that to make all in one more robust, we need its URL to have the same depth as the episodes. Using the permalink `/aio/index.html` allows us to do this.
* Having the code in a file in `_includes` makes it easier to update its content when maintainers want to update the version of the template. 
* I'm also wondering if we could use a more explicit name:
  - `all`
  - `combined`
  - `all_episodes`

### CODE REVIEW

**Comment by maxim-belkin** [comment]
>     * Having the code in a file in `_includes` makes it easier to update its content when maintainers want to update the version of the template.

This is, actually, a nice idea that we can use the same approach for "figures.md" (and any other content that is shared across all repos).

**Comment by maxim-belkin** [comment]
1. Can we move `bin/boilerplate/aio.md` to the root folder?
2. Shall we add a note (to both `aio.md` files) that there is no need to modify them.
3. Shall we call `aio.md` in `_includes` directory something like `aio-base.md` (or `-core` or `-something`)?

**Comment by fmichonneau** [comment]
> 1. Can we move `bin/boilerplate/aio.md` to the root folder?

Yes we can. I think that `aio.md` shouldn't be in `boilerplate` though. `boilerplate` should only include files that are intended to be customized by the lesson maintainers. But it's something I'd like to revisit soon as we are planning the transition to using remote themes in more detail.

> 2. Shall we add a note (to both `aio.md` files) that there is no need to modify them.

Sure.

> 3. Shall we call `aio.md` in `_includes` directory something like `aio-base.md` (or `-core` or `-something`)?

that sounds good. How about `aio-body.md`? or `aio-content.md`, or maybe `aio-script.html`?

**Comment by maxim-belkin** [comment]
> I think that `aio.md` shouldn't be in `boilerplate`

So, why don't we move it from boilerplate to the root in this PR? :)

**Comment by maxim-belkin** [comment]
I like `aio-script`, `aio-core`, and `aio-base`.

**Comment by fmichonneau** [comment]
@maxim-belkin could you please merge if it looks good to you?

**Pull request merged**
